import os
import threading
from typing import Optional, Sequence

_lock = threading.Lock()
_dotenv_loaded = False
_dotenv_path = ".env"

KEY_DEBUG = "DEBUG"
KEY_ADB_PATH = "ADB_PATH"
KEY_ADB_SERIAL = "ADB_SERIAL"
KEY_MINERU_CMD = "MINERU_CMD"
KEY_MHXY_MAP_ROI = "MHXY_MAP_ROI"
KEY_ANDROID_COORD_ROI = "ANDROID_COORD_ROI"
KEY_BATTLE_CALCULATION_ROI = "BATTLE_CALCULATION_ROI"
KEY_ANDROID_MATCH_THRESHOLD = "ANDROID_MATCH_THRESHOLD"
KEY_ANDROID_STEP_SLEEP_S = "ANDROID_STEP_SLEEP_S"
KEY_ANDROID_STEP_SLEEP_S_WORD_PUZZLE = "ANDROID_STEP_SLEEP_S_WORD_PUZZLE"

KEY_ANDROID_ADB_IME_ID = "ANDROID_ADB_IME_ID"
KEY_ANDROID_SOGOU_IME_ID = "ANDROID_SOGOU_IME_ID"

KEY_ANDROID_ARRIVAL_MAX_WAIT_S = "ANDROID_ARRIVAL_MAX_WAIT_S"
KEY_ANDROID_ARRIVAL_CHECK_INTERVAL_S = "ANDROID_ARRIVAL_CHECK_INTERVAL_S"
KEY_ANDROID_ARRIVAL_STABLE_COUNT = "ANDROID_ARRIVAL_STABLE_COUNT"

KEY_SILICONFLOW_API_KEY = "SILICONFLOW_API_KEY"
KEY_SILICONFLOW_BASE_URL = "SILICONFLOW_BASE_URL"
KEY_SILICONFLOW_OCR_MODEL = "SILICONFLOW_OCR_MODEL"
KEY_SILICONFLOW_QWEN_MODEL = "SILICONFLOW_QWEN_MODEL"
KEY_SILICONFLOW_ENABLE_THINKING = "SILICONFLOW_ENABLE_THINKING"
KEY_SILICONFLOW_TIMEOUT_S = "SILICONFLOW_TIMEOUT_S"

ADB_PATH = "adb"

ANDROID_MATCH_THRESHOLD = 0.8
ANDROID_STEP_SLEEP_S = 0.4
ANDROID_STEP_SLEEP_S_WORD_PUZZLE = 0.25

ANDROID_THR_MAP_BUTTON = 0.6
ANDROID_THR_MAP_X = ANDROID_MATCH_THRESHOLD
ANDROID_THR_MAP_Y = ANDROID_MATCH_THRESHOLD
ANDROID_THR_MAP_GO = ANDROID_MATCH_THRESHOLD

ANDROID_ADB_IME_ID = "com.android.adbkeyboard/.AdbIME"
ANDROID_SOGOU_IME_ID = "com.sohu.inputmethod.sogou.xiaomi/.SogouIME"

ANDROID_ARRIVAL_MAX_WAIT_S = 120.0
ANDROID_ARRIVAL_CHECK_INTERVAL_S = 0.5
ANDROID_ARRIVAL_STABLE_COUNT = 2

ANDROID_THR_MENU_DAOJU = ANDROID_MATCH_THRESHOLD
ANDROID_THR_PROP_FEIXINGFU = ANDROID_MATCH_THRESHOLD
ANDROID_THR_PROP_USE = ANDROID_MATCH_THRESHOLD
ANDROID_THR_FEIXINGFU_MAP = ANDROID_MATCH_THRESHOLD
ANDROID_THR_DAOJU_CLOSE = ANDROID_MATCH_THRESHOLD
ANDROID_THR_SYSTEM_TRANSFER = ANDROID_MATCH_THRESHOLD
ANDROID_TRANSFER_RETRY = 10
ANDROID_TRANSFER_RETRY_SLEEP_S = ANDROID_STEP_SLEEP_S

ANDROID_THR_SYSTEM_CLOSE_GUIDE = ANDROID_MATCH_THRESHOLD
ANDROID_THR_SYSTEM_CLOSE_TASK = ANDROID_MATCH_THRESHOLD
ANDROID_THR_SYSTEM_HIDE_DIALOG = ANDROID_MATCH_THRESHOLD
ANDROID_THR_SYSTEM_AUTO_ATTACK_SHRINK = ANDROID_MATCH_THRESHOLD
ANDROID_THR_SYSTEM_EXPAND = ANDROID_MATCH_THRESHOLD
ANDROID_THR_SYSTEM_HIDE_UI_DISABLE = ANDROID_MATCH_THRESHOLD
ANDROID_THR_SYSTEM_HIDE_PLAYER_DISABLE = ANDROID_MATCH_THRESHOLD
ANDROID_THR_SYSTEM_BACK = ANDROID_MATCH_THRESHOLD

ANDROID_THR_PROP_CHANGAN_FLAG = ANDROID_MATCH_THRESHOLD
ANDROID_THR_MAP_TELEPORT_POINT = ANDROID_MATCH_THRESHOLD
ANDROID_TELEPORT_TARGET_X = 1640
ANDROID_TELEPORT_TARGET_Y = 500

ANDROID_THR_BAOTU_RECEIVE_TASK = ANDROID_MATCH_THRESHOLD
ANDROID_THR_NPC_XIAOER = 0.4
ANDROID_THR_CHANGAN_HOTEL_DOOR = ANDROID_MATCH_THRESHOLD

MHXY_MAP_ROI = ""
ANDROID_COORD_ROI = ""
BATTLE_CALCULATION_ROI = ""

ANDROID_TPL_MAP_BUTTON = "assets/android/map/map_button.jpg"
ANDROID_TPL_MAP_BUTTON_2 = "assets/android/map/map_button2.png"
ANDROID_TPL_MAP_SEARCH_ICON = "assets/android/map/map_search_icon.png"
ANDROID_TPL_MAP_INPUT_ICON = "assets/android/map/map_input_icon.png"
ANDROID_TPL_MAP_GO = "assets/android/map/map_go.jpg"
ANDROID_TPL_MAP_EXIT = "assets/android/map/map_exit.jpg"
ANDROID_TPL_MAP_DIANXIAOER = "assets/android/map/map_dianxiaoer.png"
ANDROID_TPL_MAP_ON_THE_WAY = "assets/android/map/map_on_the_way.png"
ANDROID_TPL_MENU_DAOJU = "assets/android/memu/daoju.png"
ANDROID_TPL_PROP_FEIXINGFU = "assets/android/daoju/feixingfu.png"
ANDROID_TPL_PROP_CHANGAN_FLAG = "assets/android/daoju/changandaobiaoqi.png"
ANDROID_TPL_PROP_USE = "assets/android/daoju/jiemian/shiyong.png"
ANDROID_TPL_DAOJU_CLOSE = "assets/android/daoju/jiemian/guanbi.png"
ANDROID_TPL_FEIXINGFU_MAP_AOLAIGUO = "assets/android/map/feixingfuditu/aolaiguo.png"
ANDROID_TPL_FEIXINGFU_MAP_BAOXIANGGUO = "assets/android/map/feixingfuditu/baoxiangguo.png"
ANDROID_TPL_FEIXINGFU_MAP_CHANGANCHENG = "assets/android/map/feixingfuditu/changancheng.png"
ANDROID_TPL_FEIXINGFU_MAP_CHANGSHOUCUN = "assets/android/map/feixingfuditu/changshoucun.png"
ANDROID_TPL_FEIXINGFU_MAP_JIANYECHENG = "assets/android/map/feixingfuditu/jianye.png"
ANDROID_TPL_FEIXINGFU_MAP_ZHUZIGUO = "assets/android/map/feixingfuditu/zhuziguo.png"
ANDROID_TPL_FEIXINGFU_MAP_XILIANGNVGUO = "assets/android/map/feixingfuditu/xilaingnvguo.png"
ANDROID_TPL_MAP_TELEPORT_POINT = "assets/android/map/daobiaoqiditu/chuansongdian.png"
ANDROID_TPL_BAOTU_RECEIVE_TASK = "assets/android/baotu/tingtingwufang.png"
ANDROID_TPL_BAOTU_ATTACK_TALK = "assets/android/baotu/woshilaishoushinide.png"
ANDROID_TPL_ZHAOHUANSHOU_QIANGDAO = "assets/android/zhaohuanshou/qiangdao.png"
ANDROID_TPL_CHANGAN_HOTEL_DOOR = "assets/android/changancheng/jiudianmenkou.png"
ANDROID_TPL_SYSTEM_CLOSE_GUIDE = "assets/android/system/guanbizhiyin.png"
ANDROID_TPL_SYSTEM_CLOSE_TASK = "assets/android/system/close_task.jpg"
ANDROID_TPL_SYSTEM_HIDE_DIALOG = "assets/android/system/yincangduihua.png"
ANDROID_TPL_SYSTEM_AUTO_ATTACK_SHRINK = "assets/android/system/zidonggongjisuoxiao.png"
ANDROID_TPL_SYSTEM_EXPAND = "assets/android/system/expand.jpg"
ANDROID_TPL_SYSTEM_HIDE_UI_DISABLE = "assets/android/system/yincangjiemian_disable.png"
ANDROID_TPL_SYSTEM_HIDE_PLAYER_DISABLE = "assets/android/system/yincangwanjia_disable.png"
ANDROID_TPL_SYSTEM_BACK = "assets/android/system/back.png"
ANDROID_TPL_SYSTEM_TRANSFER = "assets/android/system/transfer.jpg"
ANDROID_TPL_NPC_DIANXIAOER_1 = "assets/android/npc/dianxiaoer1.png"
ANDROID_TPL_NPC_DIANXIAOER_2 = "assets/android/npc/dianxiaoer2.png"
ANDROID_TPL_NPC_DIANXIAOER_3 = "assets/android/npc/dianxiaoer3.png"
ANDROID_TPL_NPC_CHANGAN_YIZHANLAOBAN = "assets/android/npc/changanyizhanlaoban.png"
ANDROID_TPL_NPC_JIEYINXIANNV = "assets/android/npc/jieyinxiannv.png"
ANDROID_TPL_NPC_LAOXIA = "assets/android/npc/laoxia.png"
ANDROID_TPL_NPC_TIANJIANG = "assets/android/npc/tianjiang.png"
ANDROID_TPL_CHAT_WOYAOQU = "assets/android/chat/woyaoqu.png"

ZHUZI_TO_JINGWAI = "7,4"
JINGWAI_TO_SHITUO = ""
JINGWAI_TO_MOWANG = ""
JINGWAI_TO_WUZHUANG = ""
JINGWAI_TO_PANSI = ""
CHANGAN_TO_HUANSHENG = ""
CHANGAN_FLY_YIZHANLAOBAN = ""
CHANGAN_FLY_JIUDIAN = ""
CHANGAN_FLY_YEWAI = ""
GUOJING_TO_DIFU = ""
GUOJING_TO_PUTUO = ""
GUOJING_TO_JINGWAI = ""
JIANYE_TO_DONGHAIWAN = "242,129"
AOLAI_TO_NVER = "10,135"
AOLAI_TO_HUAGUO = ""
CHANGSHOU_TO_FANGCUN = ""
CHANGSHOU_TO_CHANGSHOUJIAOWAI = ""
DONGHAIWAN_TO_LONGGONG = ""
CHANGSHOUJIAOWAI_TO_TIANGONG = ""

MINERU_CMD = ""

SILICONFLOW_API_KEY = ""
SILICONFLOW_BASE_URL = "https://api.siliconflow.cn/v1"
SILICONFLOW_OCR_MODEL = "PaddlePaddle/PaddleOCR-VL-1.5"
SILICONFLOW_QWEN_MODEL = "Qwen/Qwen3.6-VL-Plus"


def init(dotenv_path: str = ".env") -> None:
    global _dotenv_loaded, _dotenv_path
    p = str(dotenv_path or ".env").strip() or ".env"
    if _dotenv_loaded and p == _dotenv_path:
        return
    with _lock:
        if _dotenv_loaded and p == _dotenv_path:
            return
        _dotenv_path = p
        _load_dotenv(p)
        _dotenv_loaded = True


def _load_dotenv(path: str) -> None:
    if not path:
        return
    if not os.path.exists(path):
        return
    try:
        with open(path, "r", encoding="utf-8") as f:
            for raw_line in f:
                line = raw_line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, value = line.split("=", 1)
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if key and key not in os.environ:
                    os.environ[key] = value
    except OSError:
        return


def env_str(key: str, default: str = "") -> str:
    init()
    v = os.getenv(str(key), "")
    s = str(v or "").strip()
    if s:
        return s
    return str(default or "")


_MHXY_MAP_ROI_DEFAULT = MHXY_MAP_ROI
MHXY_MAP_ROI = env_str(KEY_MHXY_MAP_ROI, _MHXY_MAP_ROI_DEFAULT)

_ANDROID_COORD_ROI_DEFAULT = ANDROID_COORD_ROI
ANDROID_COORD_ROI = env_str(KEY_ANDROID_COORD_ROI, _ANDROID_COORD_ROI_DEFAULT)

_BATTLE_CALCULATION_ROI_DEFAULT = BATTLE_CALCULATION_ROI
BATTLE_CALCULATION_ROI = env_str(KEY_BATTLE_CALCULATION_ROI, _BATTLE_CALCULATION_ROI_DEFAULT)

_ANDROID_TPL_MAP_BUTTON_DEFAULT = ANDROID_TPL_MAP_BUTTON
ANDROID_TPL_MAP_BUTTON = env_str("ANDROID_TPL_MAP_BUTTON", _ANDROID_TPL_MAP_BUTTON_DEFAULT)

_ANDROID_TPL_MAP_BUTTON_2_DEFAULT = ANDROID_TPL_MAP_BUTTON_2
ANDROID_TPL_MAP_BUTTON_2 = env_str("ANDROID_TPL_MAP_BUTTON_2", _ANDROID_TPL_MAP_BUTTON_2_DEFAULT)

_ANDROID_TPL_MAP_SEARCH_ICON_DEFAULT = ANDROID_TPL_MAP_SEARCH_ICON
ANDROID_TPL_MAP_SEARCH_ICON = env_str("ANDROID_TPL_MAP_SEARCH_ICON", _ANDROID_TPL_MAP_SEARCH_ICON_DEFAULT)

_ANDROID_TPL_MAP_INPUT_ICON_DEFAULT = ANDROID_TPL_MAP_INPUT_ICON
ANDROID_TPL_MAP_INPUT_ICON = env_str("ANDROID_TPL_MAP_INPUT_ICON", _ANDROID_TPL_MAP_INPUT_ICON_DEFAULT)

_ANDROID_TPL_MAP_GO_DEFAULT = ANDROID_TPL_MAP_GO
ANDROID_TPL_MAP_GO = env_str("ANDROID_TPL_MAP_GO", _ANDROID_TPL_MAP_GO_DEFAULT)

_ANDROID_TPL_MAP_EXIT_DEFAULT = ANDROID_TPL_MAP_EXIT
ANDROID_TPL_MAP_EXIT = env_str("ANDROID_TPL_MAP_EXIT", _ANDROID_TPL_MAP_EXIT_DEFAULT)

_ANDROID_TPL_MAP_DIANXIAOER_DEFAULT = ANDROID_TPL_MAP_DIANXIAOER
ANDROID_TPL_MAP_DIANXIAOER = env_str("ANDROID_TPL_MAP_DIANXIAOER", _ANDROID_TPL_MAP_DIANXIAOER_DEFAULT)

_ANDROID_TPL_MAP_ON_THE_WAY_DEFAULT = ANDROID_TPL_MAP_ON_THE_WAY
ANDROID_TPL_MAP_ON_THE_WAY = env_str("ANDROID_TPL_MAP_ON_THE_WAY", _ANDROID_TPL_MAP_ON_THE_WAY_DEFAULT)

_ANDROID_TPL_MENU_DAOJU_DEFAULT = ANDROID_TPL_MENU_DAOJU
ANDROID_TPL_MENU_DAOJU = env_str("ANDROID_TPL_MENU_DAOJU", _ANDROID_TPL_MENU_DAOJU_DEFAULT)

_ANDROID_TPL_PROP_FEIXINGFU_DEFAULT = ANDROID_TPL_PROP_FEIXINGFU
ANDROID_TPL_PROP_FEIXINGFU = env_str("ANDROID_TPL_PROP_FEIXINGFU", _ANDROID_TPL_PROP_FEIXINGFU_DEFAULT)

_ANDROID_TPL_PROP_CHANGAN_FLAG_DEFAULT = ANDROID_TPL_PROP_CHANGAN_FLAG
ANDROID_TPL_PROP_CHANGAN_FLAG = env_str("ANDROID_TPL_PROP_CHANGAN_FLAG", _ANDROID_TPL_PROP_CHANGAN_FLAG_DEFAULT)

_ANDROID_TPL_PROP_USE_DEFAULT = ANDROID_TPL_PROP_USE
ANDROID_TPL_PROP_USE = env_str("ANDROID_TPL_PROP_USE", _ANDROID_TPL_PROP_USE_DEFAULT)

_ANDROID_TPL_DAOJU_CLOSE_DEFAULT = ANDROID_TPL_DAOJU_CLOSE
ANDROID_TPL_DAOJU_CLOSE = env_str("ANDROID_TPL_DAOJU_CLOSE", _ANDROID_TPL_DAOJU_CLOSE_DEFAULT)

_ANDROID_TPL_FEIXINGFU_MAP_AOLAIGUO_DEFAULT = ANDROID_TPL_FEIXINGFU_MAP_AOLAIGUO
ANDROID_TPL_FEIXINGFU_MAP_AOLAIGUO = env_str("ANDROID_TPL_FEIXINGFU_MAP_AOLAIGUO", _ANDROID_TPL_FEIXINGFU_MAP_AOLAIGUO_DEFAULT)

_ANDROID_TPL_FEIXINGFU_MAP_BAOXIANGGUO_DEFAULT = ANDROID_TPL_FEIXINGFU_MAP_BAOXIANGGUO
ANDROID_TPL_FEIXINGFU_MAP_BAOXIANGGUO = env_str("ANDROID_TPL_FEIXINGFU_MAP_BAOXIANGGUO", _ANDROID_TPL_FEIXINGFU_MAP_BAOXIANGGUO_DEFAULT)

_ANDROID_TPL_FEIXINGFU_MAP_CHANGANCHENG_DEFAULT = ANDROID_TPL_FEIXINGFU_MAP_CHANGANCHENG
ANDROID_TPL_FEIXINGFU_MAP_CHANGANCHENG = env_str("ANDROID_TPL_FEIXINGFU_MAP_CHANGANCHENG", _ANDROID_TPL_FEIXINGFU_MAP_CHANGANCHENG_DEFAULT)

_ANDROID_TPL_FEIXINGFU_MAP_CHANGSHOUCUN_DEFAULT = ANDROID_TPL_FEIXINGFU_MAP_CHANGSHOUCUN
ANDROID_TPL_FEIXINGFU_MAP_CHANGSHOUCUN = env_str("ANDROID_TPL_FEIXINGFU_MAP_CHANGSHOUCUN", _ANDROID_TPL_FEIXINGFU_MAP_CHANGSHOUCUN_DEFAULT)

_ANDROID_TPL_FEIXINGFU_MAP_JIANYECHENG_DEFAULT = ANDROID_TPL_FEIXINGFU_MAP_JIANYECHENG
ANDROID_TPL_FEIXINGFU_MAP_JIANYECHENG = env_str("ANDROID_TPL_FEIXINGFU_MAP_JIANYECHENG", _ANDROID_TPL_FEIXINGFU_MAP_JIANYECHENG_DEFAULT)

_ANDROID_TPL_FEIXINGFU_MAP_ZHUZIGUO_DEFAULT = ANDROID_TPL_FEIXINGFU_MAP_ZHUZIGUO
ANDROID_TPL_FEIXINGFU_MAP_ZHUZIGUO = env_str("ANDROID_TPL_FEIXINGFU_MAP_ZHUZIGUO", _ANDROID_TPL_FEIXINGFU_MAP_ZHUZIGUO_DEFAULT)

_ANDROID_TPL_FEIXINGFU_MAP_XILIANGNVGUO_DEFAULT = ANDROID_TPL_FEIXINGFU_MAP_XILIANGNVGUO
ANDROID_TPL_FEIXINGFU_MAP_XILIANGNVGUO = env_str("ANDROID_TPL_FEIXINGFU_MAP_XILIANGNVGUO", _ANDROID_TPL_FEIXINGFU_MAP_XILIANGNVGUO_DEFAULT)

_ANDROID_TPL_MAP_TELEPORT_POINT_DEFAULT = ANDROID_TPL_MAP_TELEPORT_POINT
ANDROID_TPL_MAP_TELEPORT_POINT = env_str("ANDROID_TPL_MAP_TELEPORT_POINT", _ANDROID_TPL_MAP_TELEPORT_POINT_DEFAULT)

_ANDROID_TPL_BAOTU_RECEIVE_TASK_DEFAULT = ANDROID_TPL_BAOTU_RECEIVE_TASK
ANDROID_TPL_BAOTU_RECEIVE_TASK = env_str("ANDROID_TPL_BAOTU_RECEIVE_TASK", _ANDROID_TPL_BAOTU_RECEIVE_TASK_DEFAULT)

_ANDROID_TPL_BAOTU_ATTACK_TALK_DEFAULT = ANDROID_TPL_BAOTU_ATTACK_TALK
ANDROID_TPL_BAOTU_ATTACK_TALK = env_str("ANDROID_TPL_BAOTU_ATTACK_TALK", _ANDROID_TPL_BAOTU_ATTACK_TALK_DEFAULT)

_ANDROID_TPL_ZHAOHUANSHOU_QIANGDAO_DEFAULT = ANDROID_TPL_ZHAOHUANSHOU_QIANGDAO
ANDROID_TPL_ZHAOHUANSHOU_QIANGDAO = env_str(
    "ANDROID_TPL_ZHAOHUANSHOU_QIANGDAO",
    _ANDROID_TPL_ZHAOHUANSHOU_QIANGDAO_DEFAULT,
)

_ANDROID_TPL_CHANGAN_HOTEL_DOOR_DEFAULT = ANDROID_TPL_CHANGAN_HOTEL_DOOR
ANDROID_TPL_CHANGAN_HOTEL_DOOR = env_str("ANDROID_TPL_CHANGAN_HOTEL_DOOR", _ANDROID_TPL_CHANGAN_HOTEL_DOOR_DEFAULT)

_ANDROID_TPL_SYSTEM_CLOSE_GUIDE_DEFAULT = ANDROID_TPL_SYSTEM_CLOSE_GUIDE
ANDROID_TPL_SYSTEM_CLOSE_GUIDE = env_str("ANDROID_TPL_SYSTEM_CLOSE_GUIDE", _ANDROID_TPL_SYSTEM_CLOSE_GUIDE_DEFAULT)

_ANDROID_TPL_SYSTEM_CLOSE_TASK_DEFAULT = ANDROID_TPL_SYSTEM_CLOSE_TASK
ANDROID_TPL_SYSTEM_CLOSE_TASK = env_str("ANDROID_TPL_SYSTEM_CLOSE_TASK", _ANDROID_TPL_SYSTEM_CLOSE_TASK_DEFAULT)

_ANDROID_TPL_SYSTEM_HIDE_DIALOG_DEFAULT = ANDROID_TPL_SYSTEM_HIDE_DIALOG
ANDROID_TPL_SYSTEM_HIDE_DIALOG = env_str("ANDROID_TPL_SYSTEM_HIDE_DIALOG", _ANDROID_TPL_SYSTEM_HIDE_DIALOG_DEFAULT)

_ANDROID_TPL_SYSTEM_AUTO_ATTACK_SHRINK_DEFAULT = ANDROID_TPL_SYSTEM_AUTO_ATTACK_SHRINK
ANDROID_TPL_SYSTEM_AUTO_ATTACK_SHRINK = env_str("ANDROID_TPL_SYSTEM_AUTO_ATTACK_SHRINK", _ANDROID_TPL_SYSTEM_AUTO_ATTACK_SHRINK_DEFAULT)

_ANDROID_TPL_SYSTEM_EXPAND_DEFAULT = ANDROID_TPL_SYSTEM_EXPAND
ANDROID_TPL_SYSTEM_EXPAND = env_str("ANDROID_TPL_SYSTEM_EXPAND", _ANDROID_TPL_SYSTEM_EXPAND_DEFAULT)

_ANDROID_TPL_SYSTEM_HIDE_UI_DISABLE_DEFAULT = ANDROID_TPL_SYSTEM_HIDE_UI_DISABLE
ANDROID_TPL_SYSTEM_HIDE_UI_DISABLE = env_str("ANDROID_TPL_SYSTEM_HIDE_UI_DISABLE", _ANDROID_TPL_SYSTEM_HIDE_UI_DISABLE_DEFAULT)

_ANDROID_TPL_SYSTEM_HIDE_PLAYER_DISABLE_DEFAULT = ANDROID_TPL_SYSTEM_HIDE_PLAYER_DISABLE
ANDROID_TPL_SYSTEM_HIDE_PLAYER_DISABLE = env_str("ANDROID_TPL_SYSTEM_HIDE_PLAYER_DISABLE", _ANDROID_TPL_SYSTEM_HIDE_PLAYER_DISABLE_DEFAULT)

_ANDROID_TPL_SYSTEM_BACK_DEFAULT = ANDROID_TPL_SYSTEM_BACK
ANDROID_TPL_SYSTEM_BACK = env_str("ANDROID_TPL_SYSTEM_BACK", _ANDROID_TPL_SYSTEM_BACK_DEFAULT)

_ANDROID_TPL_SYSTEM_TRANSFER_DEFAULT = ANDROID_TPL_SYSTEM_TRANSFER
ANDROID_TPL_SYSTEM_TRANSFER = env_str("ANDROID_TPL_SYSTEM_TRANSFER", _ANDROID_TPL_SYSTEM_TRANSFER_DEFAULT)

_ANDROID_TPL_NPC_DIANXIAOER_1_DEFAULT = ANDROID_TPL_NPC_DIANXIAOER_1
ANDROID_TPL_NPC_DIANXIAOER_1 = env_str("ANDROID_TPL_NPC_DIANXIAOER_1", _ANDROID_TPL_NPC_DIANXIAOER_1_DEFAULT)

_ANDROID_TPL_NPC_DIANXIAOER_2_DEFAULT = ANDROID_TPL_NPC_DIANXIAOER_2
ANDROID_TPL_NPC_DIANXIAOER_2 = env_str("ANDROID_TPL_NPC_DIANXIAOER_2", _ANDROID_TPL_NPC_DIANXIAOER_2_DEFAULT)

_ANDROID_TPL_NPC_DIANXIAOER_3_DEFAULT = ANDROID_TPL_NPC_DIANXIAOER_3
ANDROID_TPL_NPC_DIANXIAOER_3 = env_str("ANDROID_TPL_NPC_DIANXIAOER_3", _ANDROID_TPL_NPC_DIANXIAOER_3_DEFAULT)

_ANDROID_TPL_NPC_CHANGAN_YIZHANLAOBAN_DEFAULT = ANDROID_TPL_NPC_CHANGAN_YIZHANLAOBAN
ANDROID_TPL_NPC_CHANGAN_YIZHANLAOBAN = env_str(
    "ANDROID_TPL_NPC_CHANGAN_YIZHANLAOBAN",
    _ANDROID_TPL_NPC_CHANGAN_YIZHANLAOBAN_DEFAULT,
)

_ANDROID_TPL_NPC_JIEYINXIANNV_DEFAULT = ANDROID_TPL_NPC_JIEYINXIANNV
ANDROID_TPL_NPC_JIEYINXIANNV = env_str(
    "ANDROID_TPL_NPC_JIEYINXIANNV",
    _ANDROID_TPL_NPC_JIEYINXIANNV_DEFAULT,
)

_ANDROID_TPL_NPC_LAOXIA_DEFAULT = ANDROID_TPL_NPC_LAOXIA
ANDROID_TPL_NPC_LAOXIA = env_str(
    "ANDROID_TPL_NPC_LAOXIA",
    _ANDROID_TPL_NPC_LAOXIA_DEFAULT,
)

_ANDROID_TPL_NPC_TIANJIANG_DEFAULT = ANDROID_TPL_NPC_TIANJIANG
ANDROID_TPL_NPC_TIANJIANG = env_str(
    "ANDROID_TPL_NPC_TIANJIANG",
    _ANDROID_TPL_NPC_TIANJIANG_DEFAULT,
)

_ANDROID_TPL_CHAT_WOYAOQU_DEFAULT = ANDROID_TPL_CHAT_WOYAOQU
ANDROID_TPL_CHAT_WOYAOQU = env_str("ANDROID_TPL_CHAT_WOYAOQU", _ANDROID_TPL_CHAT_WOYAOQU_DEFAULT)

_ZHUZI_TO_JINGWAI_DEFAULT = ZHUZI_TO_JINGWAI
ZHUZI_TO_JINGWAI = env_str("ZHUZI_TO_JINGWAI", _ZHUZI_TO_JINGWAI_DEFAULT)

_JINGWAI_TO_SHITUO_DEFAULT = JINGWAI_TO_SHITUO
JINGWAI_TO_SHITUO = env_str("JINGWAI_TO_SHITUO", _JINGWAI_TO_SHITUO_DEFAULT)

_JINGWAI_TO_MOWANG_DEFAULT = JINGWAI_TO_MOWANG
JINGWAI_TO_MOWANG = env_str("JINGWAI_TO_MOWANG", _JINGWAI_TO_MOWANG_DEFAULT)

_CHANGAN_TO_HUANSHENG_DEFAULT = CHANGAN_TO_HUANSHENG
CHANGAN_TO_HUANSHENG = env_str("CHANGAN_TO_HUANSHENG", _CHANGAN_TO_HUANSHENG_DEFAULT)

_CHANGAN_FLY_YIZHANLAOBAN_DEFAULT = CHANGAN_FLY_YIZHANLAOBAN
CHANGAN_FLY_YIZHANLAOBAN = env_str("CHANGAN_FLY_YIZHANLAOBAN", _CHANGAN_FLY_YIZHANLAOBAN_DEFAULT)

_CHANGAN_FLY_JIUDIAN_DEFAULT = CHANGAN_FLY_JIUDIAN
CHANGAN_FLY_JIUDIAN = env_str("CHANGAN_FLY_JIUDIAN", _CHANGAN_FLY_JIUDIAN_DEFAULT)

_CHANGAN_FLY_YEWAI_DEFAULT = CHANGAN_FLY_YEWAI
CHANGAN_FLY_YEWAI = env_str("CHANGAN_FLY_YEWAI", _CHANGAN_FLY_YEWAI_DEFAULT)

_GUOJING_TO_DIFU_DEFAULT = GUOJING_TO_DIFU
GUOJING_TO_DIFU = env_str("GUOJING_TO_DIFU", _GUOJING_TO_DIFU_DEFAULT)

_GUOJING_TO_PUTUO_DEFAULT = GUOJING_TO_PUTUO
GUOJING_TO_PUTUO = env_str("GUOJING_TO_PUTUO", _GUOJING_TO_PUTUO_DEFAULT)

_GUOJING_TO_JINGWAI_DEFAULT = GUOJING_TO_JINGWAI
GUOJING_TO_JINGWAI = env_str("GUOJING_TO_JINGWAI", _GUOJING_TO_JINGWAI_DEFAULT)

_JINGWAI_TO_WUZHUANG_DEFAULT = JINGWAI_TO_WUZHUANG
JINGWAI_TO_WUZHUANG = env_str("JINGWAI_TO_WUZHUANG", _JINGWAI_TO_WUZHUANG_DEFAULT)

_JINGWAI_TO_PANSI_DEFAULT = JINGWAI_TO_PANSI
JINGWAI_TO_PANSI = env_str("JINGWAI_TO_PANSI", _JINGWAI_TO_PANSI_DEFAULT)

_JIANYE_TO_DONGHAIWAN_DEFAULT = JIANYE_TO_DONGHAIWAN
JIANYE_TO_DONGHAIWAN = env_str("JIANYE_TO_DONGHAIWAN", _JIANYE_TO_DONGHAIWAN_DEFAULT)

_AOLAI_TO_NVER_DEFAULT = AOLAI_TO_NVER
AOLAI_TO_NVER = env_str("AOLAI_TO_NVER", _AOLAI_TO_NVER_DEFAULT)

_AOLAI_TO_HUAGUO_DEFAULT = AOLAI_TO_HUAGUO
AOLAI_TO_HUAGUO = env_str("AOLAI_TO_HUAGUO", _AOLAI_TO_HUAGUO_DEFAULT)

_CHANGSHOU_TO_FANGCUN_DEFAULT = CHANGSHOU_TO_FANGCUN
CHANGSHOU_TO_FANGCUN = env_str("CHANGSHOU_TO_FANGCUN", _CHANGSHOU_TO_FANGCUN_DEFAULT)

_CHANGSHOU_TO_CHANGSHOUJIAOWAI_DEFAULT = CHANGSHOU_TO_CHANGSHOUJIAOWAI
CHANGSHOU_TO_CHANGSHOUJIAOWAI = env_str(
    "CHANGSHOU_TO_CHANGSHOUJIAOWAI",
    _CHANGSHOU_TO_CHANGSHOUJIAOWAI_DEFAULT,
)

_DONGHAIWAN_TO_LONGGONG_DEFAULT = DONGHAIWAN_TO_LONGGONG
DONGHAIWAN_TO_LONGGONG = env_str("DONGHAIWAN_TO_LONGGONG", _DONGHAIWAN_TO_LONGGONG_DEFAULT)

_CHANGSHOUJIAOWAI_TO_TIANGONG_DEFAULT = CHANGSHOUJIAOWAI_TO_TIANGONG
CHANGSHOUJIAOWAI_TO_TIANGONG = env_str(
    "CHANGSHOUJIAOWAI_TO_TIANGONG",
    _CHANGSHOUJIAOWAI_TO_TIANGONG_DEFAULT,
)


def env_optional_str(key: str) -> Optional[str]:
    init()
    s = str(os.getenv(str(key), "") or "").strip()
    return s or None


def env_str_first(keys: Sequence[str], default: str = "") -> str:
    for k in keys:
        v = env_str(str(k), "")
        if v:
            return v
    return str(default or "")


def env_int(key: str, default: int) -> int:
    s = env_str(key, "")
    if not s:
        return int(default)
    return int(s)


def env_float(key: str, default: float) -> float:
    s = env_str(key, "")
    if not s:
        return float(default)
    return float(s)


def env_bool(key: str, default: bool = False) -> bool:
    s = env_str(key, "")
    if not s:
        return bool(default)
    v = s.strip().lower()
    if v in ("1", "true", "yes", "y", "on"):
        return True
    if v in ("0", "false", "no", "n", "off"):
        return False
    return bool(default)


_ADB_PATH_DEFAULT = ADB_PATH
ADB_PATH = env_str(KEY_ADB_PATH, _ADB_PATH_DEFAULT)

ADB_SERIAL = env_optional_str(KEY_ADB_SERIAL)

_ANDROID_MATCH_THRESHOLD_DEFAULT = ANDROID_MATCH_THRESHOLD
ANDROID_MATCH_THRESHOLD = env_float(KEY_ANDROID_MATCH_THRESHOLD, _ANDROID_MATCH_THRESHOLD_DEFAULT)

_ANDROID_STEP_SLEEP_S_DEFAULT = ANDROID_STEP_SLEEP_S
ANDROID_STEP_SLEEP_S = env_float(KEY_ANDROID_STEP_SLEEP_S, _ANDROID_STEP_SLEEP_S_DEFAULT)

_ANDROID_STEP_SLEEP_S_WORD_PUZZLE_DEFAULT = ANDROID_STEP_SLEEP_S_WORD_PUZZLE
ANDROID_STEP_SLEEP_S_WORD_PUZZLE = env_float(KEY_ANDROID_STEP_SLEEP_S_WORD_PUZZLE, _ANDROID_STEP_SLEEP_S_WORD_PUZZLE_DEFAULT)

_ANDROID_THR_MAP_BUTTON_DEFAULT = ANDROID_THR_MAP_BUTTON
ANDROID_THR_MAP_BUTTON = env_float("ANDROID_THR_MAP_BUTTON", _ANDROID_THR_MAP_BUTTON_DEFAULT)

_ANDROID_THR_MAP_X_DEFAULT = ANDROID_THR_MAP_X
ANDROID_THR_MAP_X = env_float("ANDROID_THR_MAP_X", _ANDROID_THR_MAP_X_DEFAULT)

_ANDROID_THR_MAP_Y_DEFAULT = ANDROID_THR_MAP_Y
ANDROID_THR_MAP_Y = env_float("ANDROID_THR_MAP_Y", _ANDROID_THR_MAP_Y_DEFAULT)

_ANDROID_THR_MAP_GO_DEFAULT = ANDROID_THR_MAP_GO
ANDROID_THR_MAP_GO = env_float("ANDROID_THR_MAP_GO", _ANDROID_THR_MAP_GO_DEFAULT)

_ANDROID_ADB_IME_ID_DEFAULT = ANDROID_ADB_IME_ID
ANDROID_ADB_IME_ID = env_str(KEY_ANDROID_ADB_IME_ID, _ANDROID_ADB_IME_ID_DEFAULT)

_ANDROID_SOGOU_IME_ID_DEFAULT = ANDROID_SOGOU_IME_ID
ANDROID_SOGOU_IME_ID = env_str(KEY_ANDROID_SOGOU_IME_ID, _ANDROID_SOGOU_IME_ID_DEFAULT)

_ANDROID_ARRIVAL_MAX_WAIT_S_DEFAULT = ANDROID_ARRIVAL_MAX_WAIT_S
ANDROID_ARRIVAL_MAX_WAIT_S = env_float(KEY_ANDROID_ARRIVAL_MAX_WAIT_S, _ANDROID_ARRIVAL_MAX_WAIT_S_DEFAULT)

_ANDROID_ARRIVAL_CHECK_INTERVAL_S_DEFAULT = ANDROID_ARRIVAL_CHECK_INTERVAL_S
ANDROID_ARRIVAL_CHECK_INTERVAL_S = env_float(KEY_ANDROID_ARRIVAL_CHECK_INTERVAL_S, _ANDROID_ARRIVAL_CHECK_INTERVAL_S_DEFAULT)

_ANDROID_ARRIVAL_STABLE_COUNT_DEFAULT = ANDROID_ARRIVAL_STABLE_COUNT
ANDROID_ARRIVAL_STABLE_COUNT = env_int(KEY_ANDROID_ARRIVAL_STABLE_COUNT, _ANDROID_ARRIVAL_STABLE_COUNT_DEFAULT)

_ANDROID_THR_MENU_DAOJU_DEFAULT = ANDROID_THR_MENU_DAOJU
ANDROID_THR_MENU_DAOJU = env_float("ANDROID_THR_MENU_DAOJU", _ANDROID_THR_MENU_DAOJU_DEFAULT)

_ANDROID_THR_PROP_FEIXINGFU_DEFAULT = ANDROID_THR_PROP_FEIXINGFU
ANDROID_THR_PROP_FEIXINGFU = env_float("ANDROID_THR_PROP_FEIXINGFU", _ANDROID_THR_PROP_FEIXINGFU_DEFAULT)

_ANDROID_THR_PROP_USE_DEFAULT = ANDROID_THR_PROP_USE
ANDROID_THR_PROP_USE = env_float("ANDROID_THR_PROP_USE", _ANDROID_THR_PROP_USE_DEFAULT)

_ANDROID_THR_FEIXINGFU_MAP_DEFAULT = ANDROID_THR_FEIXINGFU_MAP
ANDROID_THR_FEIXINGFU_MAP = env_float("ANDROID_THR_FEIXINGFU_MAP", _ANDROID_THR_FEIXINGFU_MAP_DEFAULT)

_ANDROID_THR_DAOJU_CLOSE_DEFAULT = ANDROID_THR_DAOJU_CLOSE
ANDROID_THR_DAOJU_CLOSE = env_float("ANDROID_THR_DAOJU_CLOSE", _ANDROID_THR_DAOJU_CLOSE_DEFAULT)

_ANDROID_THR_SYSTEM_TRANSFER_DEFAULT = ANDROID_THR_SYSTEM_TRANSFER
ANDROID_THR_SYSTEM_TRANSFER = env_float("ANDROID_THR_SYSTEM_TRANSFER", _ANDROID_THR_SYSTEM_TRANSFER_DEFAULT)

_ANDROID_TRANSFER_RETRY_DEFAULT = ANDROID_TRANSFER_RETRY
ANDROID_TRANSFER_RETRY = env_int("ANDROID_TRANSFER_RETRY", _ANDROID_TRANSFER_RETRY_DEFAULT)

_ANDROID_TRANSFER_RETRY_SLEEP_S_DEFAULT = ANDROID_TRANSFER_RETRY_SLEEP_S
ANDROID_TRANSFER_RETRY_SLEEP_S = env_float("ANDROID_TRANSFER_RETRY_SLEEP_S", _ANDROID_TRANSFER_RETRY_SLEEP_S_DEFAULT)

_ANDROID_THR_SYSTEM_CLOSE_GUIDE_DEFAULT = ANDROID_THR_SYSTEM_CLOSE_GUIDE
ANDROID_THR_SYSTEM_CLOSE_GUIDE = env_float("ANDROID_THR_SYSTEM_CLOSE_GUIDE", _ANDROID_THR_SYSTEM_CLOSE_GUIDE_DEFAULT)

_ANDROID_THR_SYSTEM_CLOSE_TASK_DEFAULT = ANDROID_THR_SYSTEM_CLOSE_TASK
ANDROID_THR_SYSTEM_CLOSE_TASK = env_float("ANDROID_THR_SYSTEM_CLOSE_TASK", _ANDROID_THR_SYSTEM_CLOSE_TASK_DEFAULT)

_ANDROID_THR_SYSTEM_HIDE_DIALOG_DEFAULT = ANDROID_THR_SYSTEM_HIDE_DIALOG
ANDROID_THR_SYSTEM_HIDE_DIALOG = env_float("ANDROID_THR_SYSTEM_HIDE_DIALOG", _ANDROID_THR_SYSTEM_HIDE_DIALOG_DEFAULT)

_ANDROID_THR_SYSTEM_AUTO_ATTACK_SHRINK_DEFAULT = ANDROID_THR_SYSTEM_AUTO_ATTACK_SHRINK
ANDROID_THR_SYSTEM_AUTO_ATTACK_SHRINK = env_float("ANDROID_THR_SYSTEM_AUTO_ATTACK_SHRINK", _ANDROID_THR_SYSTEM_AUTO_ATTACK_SHRINK_DEFAULT)

_ANDROID_THR_SYSTEM_EXPAND_DEFAULT = ANDROID_THR_SYSTEM_EXPAND
ANDROID_THR_SYSTEM_EXPAND = env_float("ANDROID_THR_SYSTEM_EXPAND", _ANDROID_THR_SYSTEM_EXPAND_DEFAULT)

_ANDROID_THR_SYSTEM_HIDE_UI_DISABLE_DEFAULT = ANDROID_THR_SYSTEM_HIDE_UI_DISABLE
ANDROID_THR_SYSTEM_HIDE_UI_DISABLE = env_float("ANDROID_THR_SYSTEM_HIDE_UI_DISABLE", _ANDROID_THR_SYSTEM_HIDE_UI_DISABLE_DEFAULT)

_ANDROID_THR_SYSTEM_HIDE_PLAYER_DISABLE_DEFAULT = ANDROID_THR_SYSTEM_HIDE_PLAYER_DISABLE
ANDROID_THR_SYSTEM_HIDE_PLAYER_DISABLE = env_float("ANDROID_THR_SYSTEM_HIDE_PLAYER_DISABLE", _ANDROID_THR_SYSTEM_HIDE_PLAYER_DISABLE_DEFAULT)

_ANDROID_THR_SYSTEM_BACK_DEFAULT = ANDROID_THR_SYSTEM_BACK
ANDROID_THR_SYSTEM_BACK = env_float("ANDROID_THR_SYSTEM_BACK", _ANDROID_THR_SYSTEM_BACK_DEFAULT)

_ANDROID_THR_PROP_CHANGAN_FLAG_DEFAULT = ANDROID_THR_PROP_CHANGAN_FLAG
ANDROID_THR_PROP_CHANGAN_FLAG = env_float("ANDROID_THR_PROP_CHANGAN_FLAG", _ANDROID_THR_PROP_CHANGAN_FLAG_DEFAULT)

_ANDROID_THR_MAP_TELEPORT_POINT_DEFAULT = ANDROID_THR_MAP_TELEPORT_POINT
ANDROID_THR_MAP_TELEPORT_POINT = env_float("ANDROID_THR_MAP_TELEPORT_POINT", _ANDROID_THR_MAP_TELEPORT_POINT_DEFAULT)

_ANDROID_TELEPORT_TARGET_X_DEFAULT = ANDROID_TELEPORT_TARGET_X
ANDROID_TELEPORT_TARGET_X = env_int("ANDROID_TELEPORT_TARGET_X", _ANDROID_TELEPORT_TARGET_X_DEFAULT)

_ANDROID_TELEPORT_TARGET_Y_DEFAULT = ANDROID_TELEPORT_TARGET_Y
ANDROID_TELEPORT_TARGET_Y = env_int("ANDROID_TELEPORT_TARGET_Y", _ANDROID_TELEPORT_TARGET_Y_DEFAULT)

_ANDROID_THR_BAOTU_RECEIVE_TASK_DEFAULT = ANDROID_THR_BAOTU_RECEIVE_TASK
ANDROID_THR_BAOTU_RECEIVE_TASK = env_float("ANDROID_THR_BAOTU_RECEIVE_TASK", _ANDROID_THR_BAOTU_RECEIVE_TASK_DEFAULT)

_ANDROID_THR_NPC_XIAOER_DEFAULT = ANDROID_THR_NPC_XIAOER
ANDROID_THR_NPC_XIAOER = env_float("ANDROID_THR_NPC_XIAOER", _ANDROID_THR_NPC_XIAOER_DEFAULT)

_ANDROID_THR_CHANGAN_HOTEL_DOOR_DEFAULT = ANDROID_THR_CHANGAN_HOTEL_DOOR
ANDROID_THR_CHANGAN_HOTEL_DOOR = env_float("ANDROID_THR_CHANGAN_HOTEL_DOOR", _ANDROID_THR_CHANGAN_HOTEL_DOOR_DEFAULT)

_MINERU_CMD_DEFAULT = MINERU_CMD
MINERU_CMD = env_str(KEY_MINERU_CMD, _MINERU_CMD_DEFAULT)

_SILICONFLOW_API_KEY_DEFAULT = SILICONFLOW_API_KEY
SILICONFLOW_API_KEY = env_str(KEY_SILICONFLOW_API_KEY, _SILICONFLOW_API_KEY_DEFAULT)

_SILICONFLOW_BASE_URL_DEFAULT = SILICONFLOW_BASE_URL
SILICONFLOW_BASE_URL = env_str(KEY_SILICONFLOW_BASE_URL, _SILICONFLOW_BASE_URL_DEFAULT)

_SILICONFLOW_OCR_MODEL_DEFAULT = SILICONFLOW_OCR_MODEL
SILICONFLOW_OCR_MODEL = env_str(KEY_SILICONFLOW_OCR_MODEL, _SILICONFLOW_OCR_MODEL_DEFAULT)

_SILICONFLOW_QWEN_MODEL_DEFAULT = SILICONFLOW_QWEN_MODEL
SILICONFLOW_QWEN_MODEL = env_str(KEY_SILICONFLOW_QWEN_MODEL, _SILICONFLOW_QWEN_MODEL_DEFAULT)

SILICONFLOW_ENABLE_THINKING = env_bool(KEY_SILICONFLOW_ENABLE_THINKING, default=False)


def siliconflow_effective_timeout_s(timeout_s: float) -> float:
    s = env_optional_str(KEY_SILICONFLOW_TIMEOUT_S)
    if s:
        return float(s)
    return float(timeout_s)


def _parse_xy(text: str) -> Optional[tuple]:
    s = str(text or "").strip()
    if not s:
        return None
    s = s.replace("，", ",")
    parts = [p.strip() for p in s.replace(" ", ",").split(",") if p.strip()]
    if len(parts) >= 2:
        try:
            return int(parts[0]), int(parts[1])
        except Exception:
            return None
    digits = []
    cur = ""
    for ch in s:
        if ch.isdigit():
            cur += ch
        else:
            if cur:
                digits.append(cur)
                cur = ""
    if cur:
        digits.append(cur)
    if len(digits) >= 2:
        try:
            return int(digits[0]), int(digits[1])
        except Exception:
            return None
    return None


WORD_PUZZLE_POINT_KEYS = {
    1: ("ANDROID_WORD_PUZZLE_POINT_1", "WORD_PUZZLE_POINT_1", "ANDROID_WORD_PUZZLE_P1", "WORD_PUZZLE_P1"),
    2: ("ANDROID_WORD_PUZZLE_POINT_2", "WORD_PUZZLE_POINT_2", "ANDROID_WORD_PUZZLE_P2", "WORD_PUZZLE_P2"),
    3: ("ANDROID_WORD_PUZZLE_POINT_3", "WORD_PUZZLE_POINT_3", "ANDROID_WORD_PUZZLE_P3", "WORD_PUZZLE_P3"),
    4: ("ANDROID_WORD_PUZZLE_POINT_4", "WORD_PUZZLE_POINT_4", "ANDROID_WORD_PUZZLE_P4", "WORD_PUZZLE_P4"),
}

WORD_PUZZLE_POINTS_DOC = "ANDROID_WORD_PUZZLE_POINT_1..4（格式 x,y）"


def word_puzzle_points_from_env() -> dict:
    init()
    pts = {}
    for i in (1, 2, 3, 4):
        keys = WORD_PUZZLE_POINT_KEYS.get(i, ())
        raw = env_str_first(keys, default="")
        xy = _parse_xy(raw)
        if xy is not None:
            pts[i] = xy
    return pts


def require_str(key: str) -> str:
    v = env_str(key, "")
    if not v:
        raise RuntimeError(f"缺少 {key}，请在环境变量或 .env 中配置")
    return v


def is_debug() -> bool:
    return env_bool(KEY_DEBUG, default=False)


def environ_copy() -> dict:
    init()
    return dict(os.environ)
